### PR TITLE
KDE KF6 update

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by travier** [comment]
https://invent.kde.org/education/marble/-/issues/12

**Comment by Erick555** [comment]
Is it an option to temporarily drop geolocation support?

**Comment by travier** [comment]
I'd say that would be up to the maintainer, but we are not yet in a hurry so we can wait a bit for the marble port to get merged.

**Comment by cgilles** [comment]
You have an option in digiKam cmake rules to disable Geolocation.

You don't need to wait for Marble, digiKam include a simplified port to Qt6 of Marble (as i never receive a response of Marble team about this topic since a very long time, so i do it).

**Comment by travier** [comment]
> You don't need to wait for Marble, digiKam include a simplified port to Qt6 of Marble (as i never receive a response of Marble team about this topic since a very long time, so i do it).

Does this mean that we can completely drop the dependency on Marble?

**Comment by Erick555** [comment]
For some reason digikam removed old tarball. News one is at https://download.kde.org/stable/digikam/8.3.0/digiKam-8.3.0-1.tar.xz

**Comment by hfiguiere** [comment]
> For some reason digikam removed old tarball. News one is at https://download.kde.org/stable/digikam/8.3.0/digiKam-8.3.0-1.tar.xz

See also https://github.com/flathub/org.kde.digikam/pull/78#issuecomment-2046838848

**Comment by Erick555** [comment]
I think you need to pass `-DBUILD_WITH_QT6=ON` for digikam ([off](https://invent.kde.org/graphics/digikam/-/blob/v8.3.0/core/cmake/rules/RulesOptionDefinitions.cmake#L27) by default)

Also remove ["cxxflags": "-isystem /app/include/KF5"](https://github.com/flathub/org.kde.digikam/blob/master/org.kde.digikam.json#L58)

**Comment by Erick555** [comment]
for mosaicwall you need to use [commit from of git branch](https://github.com/scheckmedia/ImageMosaicWall/commits/master/) since there is no qt6 compatible release yet

**Comment by travier** [comment]
Too many changes in this PR so splitting the common updates in https://github.com/flathub/org.kde.digikam/pull/80

**Comment by Erick555** [comment]
> Too many changes in this PR so splitting the common updates in #80

Since that doesn't work yet and this one does maybe merge this one and be done with digikam for a while.

**Comment by travier** [comment]
There is a ton of work to do on this Flatpak:
- Most dependencies are using Git repos instead of tarballs
- Most dependencies do not have x-checker-data info to simplify updates

**Comment by Erick555** [comment]
> Most dependencies are using Git repos instead of tarballs

are you suggesting this is wrong thing, especially after recent events?

**Comment by cgilles** [comment]
> for mosaicwall you need to use [commit from of git branch](https://github.com/scheckmedia/ImageMosaicWall/commits/master/) since there is no qt6 compatible release yet

yes mosaicwall 3rdparty plugin is not yet ported to new Exiv2/Qt6 API i open a MR i this way but it's not yet integrated.

Anyway, you can always take a look to my CD script for AppImage, Windows and MacOS which integrate the last rules to be update.

Windows bundle is Qt6 based now. So mosaiwall plugin is patched like this :

https://invent.kde.org/graphics/digikam/-/tree/master/project/bundles/3rdparty/ext_mosaicwall?ref_type=heads

Gilles

**Comment by travier** [comment]
> are you suggesting this is wrong thing, especially after recent events?

Yes, it's about cost saving for the Flathub infra. We're not going to stop using tarball because one project's tarballs were compromised.

**Comment by Erick555** [comment]
f-b does [shallow clones](https://github.com/flatpak/flatpak-builder/commit/be8597f3465408f6213c0b9f0ab47eaacbafbf2f) so I'm not sure where are the cost savings. git has transparency that tarballs lack.

**Comment by travier** [comment]
Yes, this is better than full a clone but still significantly slower and less CPU efficient than downloading a tarball.

Anyway, this is a general KDE Apps on Flathub "policy" and orthogonal to this issue.

**Comment by Erick555** [comment]
Ok, is there anything left do to for this PR?

File: org.kde.digikam.json [hunk 1]
```diff
@@ -1,9 +1,9 @@
 {
     "id": "org.kde.digikam",
     "base": "io.qt.qtwebengine.BaseApp",
-    "base-version": "5.15-23.08",
+    "base-version": "6.6",
     "runtime": "org.kde.Platform",
-    "runtime-version": "5.15-23.08",
+    "runtime-version": "6.6",
```
Comment (Erick555) [inline org.kde.digikam.json:6]: Maybe it's better to move directly to 6.7 to prevent switching runtime again in short period. Qt 6.6 is no longer supported.

Comment (cgilles) [reply org.kde.digikam.json:6]: warning : qt 6.7 force to switch to C++20 instead C++17 which can be side effects. digikam compile but new complex warnings appears and are not yet fixed...

Comment (tsdgeos) [reply org.kde.digikam.json:6]: "Qt 6.6 is no longer supported" is a very strong wording that is not quite true on the general meaning of "supported"

Comment (Erick555) [reply org.kde.digikam.json:6]: It means there will be no more releases/fixes for that branch so reporting bug will be ineffective. This is general meaning of _unsupported_ in software world.

Comment (Erick555) [reply org.kde.digikam.json:6]: I meant there will be no more releases/fixes for that branch so reporting bug will be ineffective.

Comment (Erick555) [reply org.kde.digikam.json:6]: It means there will be no more releases/fixes for that branch so fixing a bug will require update to next version for example.

Comment (travier) [reply org.kde.digikam.json:6]: The 6.6 runtime will still be there for a while. This PR already does a lot. Let's not add more.

**Comment by travier** [comment]
The application appears to be working, but it requires full home access to be useful :/. We're in the same boat as Elisa for example.

**Comment by travier** [comment]
The diff with the previous push is in https://github.com/flathub/org.kde.digikam/compare/30bfd155375b831509e0913f64e2502329008fc0..fea613195c6b5cd43687dc4a9951f153e3178d76 and I did not touch hugin, which is failing now :/

**Comment by Erick555** [comment]
The error is:

> /run/build/hugin/src/tools/pto_move.cpp: In function ‘bool PTOCopyMove(bool, boost::filesystem::path, boost::filesystem::path, bool)’:
> /run/build/hugin/src/hugin_base/hugin_utils/filesystem.h:67:51: error: ‘boost::filesystem::copy_option’ has not been declared
>    67 |     #define OVERWRITE_EXISTING boost::filesystem::copy_option::overwrite_if_exists

Last working build had [boost 1.84](https://buildbot.flathub.org/api/v2/logs/4443281/raw) (boost_1_84_0.tar.bz2)

Broken build has [boost 1.85](https://buildbot.flathub.org/api/v2/logs/4462805/raw) (boost_1_85_0.tar.bz2)

**Comment by Erick555** [comment]
You can even spot boost was broken in https://github.com/flathub/org.kde.digikam/pull/81

**Comment by travier** [comment]
OK, this one works well for me as far as I could test.  @cgilles Could you give it a try? Thanks!

**Comment by edisso999** [comment]
Ready for release?

**Comment by travier** [comment]
Thanks a lot for the feedback!

**Comment by edisso999** [comment]
Master did not build...

**Comment by travier** [comment]
```
{
    "errors": [
        "module-mosaicwall-source-git-branch"
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
```

https://docs.flathub.org/docs/for-app-authors/linter/#module-module_name-source-git-branch

**Comment by travier** [comment]
making a fix

File: org.kde.digikam.json [hunk 2]
```diff
@@ -1,16 +1,17 @@
...
     "sdk": "org.kde.Sdk",
     "command": "digikam",
     "finish-args": [
         "--device=all",
-        "--filesystem=xdg-pictures",
         "--filesystem=/media",
         "--filesystem=/run/media",
+        "--filesystem=home",
+        "--filesystem=xdg-pictures",
```
Comment (hfiguiere) [inline org.kde.digikam.json:14]: this is redundant with the line above it.

**Comment by zWhdmB5T** [comment]
@travier  Thank you very much for this large (and actually now) working update!

File: org.kde.digikam.json (hunk 2 above)
Comment (hfiguiere) [reply org.kde.digikam.json:14]: I don't agree. but that's not the first time.

Comment (travier) [reply org.kde.digikam.json:14]: I filed https://github.com/flathub/org.kde.digikam/issues/85 to track that. As this is not a pressing issue right, we can revisit that later.
